// Import the Zod library for schema validation
import { z } from 'zod';

// Define the schema for a Jakoryhma (group)
export const JakoryhmaSchema = z.object({
  // The ryhma_id is optional because it might be autogenerated by the database
  ryhma_id: z.number().optional(),
  // seurue_id must be a number and is required
  seurue_id: z.number(),
  // ryhman_nimi must be a string and should not exceed 50 characters
  ryhman_nimi: z.string().max(50),
});